_this enableSimulation false;
_this allowDamage false;
_this addAction[format["%1 (%2€)",["license_med_air"] call life_fnc_varToStr,[(["mair"] call life_fnc_licensePrice)] call life_fnc_numberText],life_fnc_buyLicense,"mair",0,false,false,"",' !license_med_air && playerSide == independent '];  
_this addAction["Magasin Médecin",life_fnc_weaponShopMenu,"med_basic"];  this addAction["Véhicule Médical",life_fnc_vehicleShopMenu,["med_shop",independent,"med_car_1","med","Kavala Hosptial"]];  
_this addAction["Helicopter Médical",life_fnc_vehicleShopMenu,["med_air_hs",independent,"medic_spawn_1","med","Kavala Hosptial"]];  
_this addAction["Helicopter DLC Médical",life_fnc_vehicleShopMenu,["med_air_dlc",independent,"medic_spawn_1","med","Kavala Hosptial"]];
_this addAction["Garage",  {   [[getPlayerUID player,playerSide,"Car",player],"TON_fnc_getVehicles",false,false] spawn life_fnc_MP;   createDialog "Life_impound_menu";   disableSerialization;   ctrlSetText[2802,"Recherche...."];   life_garage_sp = "med_car_1"; life_garage_type = "Car";  },"",0,false,false,"",'playerSide == independent '];  
_this addAction["Helicopter Garage",  {   [[getPlayerUID player,playerSide,"Air",player],"TON_fnc_getVehicles",false,false] spawn life_fnc_MP;   createDialog "Life_impound_menu";   disableSerialization;   ctrlSetText[2802,"Recherche...."];   life_garage_sp = "medic_spawn_1"; life_garage_type = "Air";  },"",0,false,false,"",'playerSide == independent '];  
_this addAction["Ranger Véhicule",life_fnc_storeVehicle,"",0,false,false,"",'!life_garage_store']; 
_this setObjectTexture [0,"sg_pack01\textures\medic_uniform.jpg"];